name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: Build the Docker image
        run: docker build . -f Dockerfile -t $DOCKERHUB_USERNAME/node-argo-k8s:$GITHUB_SHA

      - name: Push the Docker image
        run: docker push $DOCKERHUB_USERNAME/node-argo-k8s:$GITHUB_SHA
