name: Build and Push Docker Image

on:
  push:
    branches: [ 'main' ]
    paths: ['source-code/**']
  pull_request:
    branches: [ 'main' ]
    paths: ['source-code/**']

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4

      - name: docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: Build the Docker image
        working-directory: ./source-code
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build . -f Dockerfile -t $DOCKERHUB_USERNAME/node-argo-k8s:${GITHUB_SHA::7}

      - name: Push the Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $DOCKERHUB_USERNAME/node-argo-k8s:${GITHUB_SHA::7}

      - name: Update the Docker image tag in the values.yaml
        uses: OpsVerseIO/image-updater-action@0.1.0
        with:
          valueFile: ./node-argo-k8s-helm/values.yaml
          propertyPath: 'image.tag'
          value: ${GITHUB_SHA::7}
          branch: main/${GITHUB_SHA::7}
          targetBranch: main
          createPR: true
          message: 'Updated the image tag to ${GITHUB_SHA::7}'