name: Build and Push Docker Image

on:
  push:
    branches: [ 'main' ]
    paths: ['source-code/**']
  pull_request:
    branches: [ 'main' ]
    paths: ['source-code/**']

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4

      - name: docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: Build the Docker image
        working-directory: ./source-code
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build . -f Dockerfile -t $DOCKERHUB_USERNAME/node-argo-k8s:${GITHUB_SHA::7}

      - name: Push the Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $DOCKERHUB_USERNAME/node-argo-k8s:${GITHUB_SHA::7}

      - name: Update values.yaml
        run: |
          sed -i 's/latest/'"${GITHUB_SHA::7}"'/' node-argo-k8s-helm/values.yaml 
#sed -i 's/tag:.*/tag: '"${GITHUB_SHA::7}"'/' node-argo-k8s-helm/values.yaml
